/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployerIndexRouteImport } from './routes/employer.index'
import { Route as ClinicIndexRouteImport } from './routes/clinic.index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as EmployerRosterRouteImport } from './routes/employer.roster'
import { Route as EmployerNotificationsRouteImport } from './routes/employer.notifications'
import { Route as EmployerComplianceRouteImport } from './routes/employer.compliance'
import { Route as EmployerBillingRouteImport } from './routes/employer.billing'
import { Route as EmployerAppointmentsRouteImport } from './routes/employer.appointments'
import { Route as ClinicSlotsRouteImport } from './routes/clinic.slots'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AppRecordsRouteImport } from './routes/app.records'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppEmergencyRouteImport } from './routes/app.emergency'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppBookRouteImport } from './routes/app.book'
import { Route as AppAppointmentsIdRouteImport } from './routes/app.appointments.$id'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth.lazy').then((d) => d.Route))
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerIndexRoute = EmployerIndexRouteImport.update({
  id: '/employer/',
  path: '/employer/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicIndexRoute = ClinicIndexRouteImport.update({
  id: '/clinic/',
  path: '/clinic/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/auth.index.lazy').then((d) => d.Route))
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRosterRoute = EmployerRosterRouteImport.update({
  id: '/employer/roster',
  path: '/employer/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerNotificationsRoute = EmployerNotificationsRouteImport.update({
  id: '/employer/notifications',
  path: '/employer/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerComplianceRoute = EmployerComplianceRouteImport.update({
  id: '/employer/compliance',
  path: '/employer/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerBillingRoute = EmployerBillingRouteImport.update({
  id: '/employer/billing',
  path: '/employer/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerAppointmentsRoute = EmployerAppointmentsRouteImport.update({
  id: '/employer/appointments',
  path: '/employer/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicSlotsRoute = ClinicSlotsRouteImport.update({
  id: '/clinic/slots',
  path: '/clinic/slots',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/auth.verify.lazy').then((d) => d.Route))
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/auth.reset.lazy').then((d) => d.Route))
const AppRecordsRoute = AppRecordsRouteImport.update({
  id: '/app/records',
  path: '/app/records',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/app/notifications',
  path: '/app/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEmergencyRoute = AppEmergencyRouteImport.update({
  id: '/app/emergency',
  path: '/app/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/app/chat',
  path: '/app/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBookRoute = AppBookRouteImport.update({
  id: '/app/book',
  path: '/app/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppointmentsIdRoute = AppAppointmentsIdRouteImport.update({
  id: '/app/appointments/$id',
  path: '/app/appointments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/app/book': typeof AppBookRoute
  '/app/chat': typeof AppChatRoute
  '/app/emergency': typeof AppEmergencyRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/records': typeof AppRecordsRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/clinic/slots': typeof ClinicSlotsRoute
  '/employer/appointments': typeof EmployerAppointmentsRoute
  '/employer/billing': typeof EmployerBillingRoute
  '/employer/compliance': typeof EmployerComplianceRoute
  '/employer/notifications': typeof EmployerNotificationsRoute
  '/employer/roster': typeof EmployerRosterRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/clinic/': typeof ClinicIndexRoute
  '/employer/': typeof EmployerIndexRoute
  '/app/appointments/$id': typeof AppAppointmentsIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app/book': typeof AppBookRoute
  '/app/chat': typeof AppChatRoute
  '/app/emergency': typeof AppEmergencyRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/records': typeof AppRecordsRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/clinic/slots': typeof ClinicSlotsRoute
  '/employer/appointments': typeof EmployerAppointmentsRoute
  '/employer/billing': typeof EmployerBillingRoute
  '/employer/compliance': typeof EmployerComplianceRoute
  '/employer/notifications': typeof EmployerNotificationsRoute
  '/employer/roster': typeof EmployerRosterRoute
  '/app': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/clinic': typeof ClinicIndexRoute
  '/employer': typeof EmployerIndexRoute
  '/app/appointments/$id': typeof AppAppointmentsIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/app/book': typeof AppBookRoute
  '/app/chat': typeof AppChatRoute
  '/app/emergency': typeof AppEmergencyRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/records': typeof AppRecordsRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/clinic/slots': typeof ClinicSlotsRoute
  '/employer/appointments': typeof EmployerAppointmentsRoute
  '/employer/billing': typeof EmployerBillingRoute
  '/employer/compliance': typeof EmployerComplianceRoute
  '/employer/notifications': typeof EmployerNotificationsRoute
  '/employer/roster': typeof EmployerRosterRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/clinic/': typeof ClinicIndexRoute
  '/employer/': typeof EmployerIndexRoute
  '/app/appointments/$id': typeof AppAppointmentsIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/app/book'
    | '/app/chat'
    | '/app/emergency'
    | '/app/notifications'
    | '/app/profile'
    | '/app/records'
    | '/auth/reset'
    | '/auth/verify'
    | '/clinic/slots'
    | '/employer/appointments'
    | '/employer/billing'
    | '/employer/compliance'
    | '/employer/notifications'
    | '/employer/roster'
    | '/app/'
    | '/auth/'
    | '/clinic/'
    | '/employer/'
    | '/app/appointments/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/app/book'
    | '/app/chat'
    | '/app/emergency'
    | '/app/notifications'
    | '/app/profile'
    | '/app/records'
    | '/auth/reset'
    | '/auth/verify'
    | '/clinic/slots'
    | '/employer/appointments'
    | '/employer/billing'
    | '/employer/compliance'
    | '/employer/notifications'
    | '/employer/roster'
    | '/app'
    | '/auth'
    | '/clinic'
    | '/employer'
    | '/app/appointments/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/app/book'
    | '/app/chat'
    | '/app/emergency'
    | '/app/notifications'
    | '/app/profile'
    | '/app/records'
    | '/auth/reset'
    | '/auth/verify'
    | '/clinic/slots'
    | '/employer/appointments'
    | '/employer/billing'
    | '/employer/compliance'
    | '/employer/notifications'
    | '/employer/roster'
    | '/app/'
    | '/auth/'
    | '/clinic/'
    | '/employer/'
    | '/app/appointments/$id'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRouteWithChildren
  AppBookRoute: typeof AppBookRoute
  AppChatRoute: typeof AppChatRoute
  AppEmergencyRoute: typeof AppEmergencyRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRecordsRoute: typeof AppRecordsRoute
  ClinicSlotsRoute: typeof ClinicSlotsRoute
  EmployerAppointmentsRoute: typeof EmployerAppointmentsRoute
  EmployerBillingRoute: typeof EmployerBillingRoute
  EmployerComplianceRoute: typeof EmployerComplianceRoute
  EmployerNotificationsRoute: typeof EmployerNotificationsRoute
  EmployerRosterRoute: typeof EmployerRosterRoute
  AppIndexRoute: typeof AppIndexRoute
  ClinicIndexRoute: typeof ClinicIndexRoute
  EmployerIndexRoute: typeof EmployerIndexRoute
  AppAppointmentsIdRoute: typeof AppAppointmentsIdRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/': {
      id: '/employer/'
      path: '/employer'
      fullPath: '/employer/'
      preLoaderRoute: typeof EmployerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/': {
      id: '/clinic/'
      path: '/clinic'
      fullPath: '/clinic/'
      preLoaderRoute: typeof ClinicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/roster': {
      id: '/employer/roster'
      path: '/employer/roster'
      fullPath: '/employer/roster'
      preLoaderRoute: typeof EmployerRosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/notifications': {
      id: '/employer/notifications'
      path: '/employer/notifications'
      fullPath: '/employer/notifications'
      preLoaderRoute: typeof EmployerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/compliance': {
      id: '/employer/compliance'
      path: '/employer/compliance'
      fullPath: '/employer/compliance'
      preLoaderRoute: typeof EmployerComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/billing': {
      id: '/employer/billing'
      path: '/employer/billing'
      fullPath: '/employer/billing'
      preLoaderRoute: typeof EmployerBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer/appointments': {
      id: '/employer/appointments'
      path: '/employer/appointments'
      fullPath: '/employer/appointments'
      preLoaderRoute: typeof EmployerAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/slots': {
      id: '/clinic/slots'
      path: '/clinic/slots'
      fullPath: '/clinic/slots'
      preLoaderRoute: typeof ClinicSlotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/records': {
      id: '/app/records'
      path: '/app/records'
      fullPath: '/app/records'
      preLoaderRoute: typeof AppRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/app/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/emergency': {
      id: '/app/emergency'
      path: '/app/emergency'
      fullPath: '/app/emergency'
      preLoaderRoute: typeof AppEmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/app/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/book': {
      id: '/app/book'
      path: '/app/book'
      fullPath: '/app/book'
      preLoaderRoute: typeof AppBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/appointments/$id': {
      id: '/app/appointments/$id'
      path: '/app/appointments/$id'
      fullPath: '/app/appointments/$id'
      preLoaderRoute: typeof AppAppointmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthResetRoute: typeof AuthResetRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetRoute: AuthResetRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRouteWithChildren,
  AppBookRoute: AppBookRoute,
  AppChatRoute: AppChatRoute,
  AppEmergencyRoute: AppEmergencyRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRecordsRoute: AppRecordsRoute,
  ClinicSlotsRoute: ClinicSlotsRoute,
  EmployerAppointmentsRoute: EmployerAppointmentsRoute,
  EmployerBillingRoute: EmployerBillingRoute,
  EmployerComplianceRoute: EmployerComplianceRoute,
  EmployerNotificationsRoute: EmployerNotificationsRoute,
  EmployerRosterRoute: EmployerRosterRoute,
  AppIndexRoute: AppIndexRoute,
  ClinicIndexRoute: ClinicIndexRoute,
  EmployerIndexRoute: EmployerIndexRoute,
  AppAppointmentsIdRoute: AppAppointmentsIdRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
