/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppRecordsRouteImport } from './routes/app.records'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppBookRouteImport } from './routes/app.book'
import { Route as AppAppointmentsIdRouteImport } from './routes/app.appointments.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRecordsRoute = AppRecordsRouteImport.update({
  id: '/app/records',
  path: '/app/records',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/app/chat',
  path: '/app/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBookRoute = AppBookRouteImport.update({
  id: '/app/book',
  path: '/app/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppointmentsIdRoute = AppAppointmentsIdRouteImport.update({
  id: '/app/appointments/$id',
  path: '/app/appointments/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/book': typeof AppBookRoute
  '/app/chat': typeof AppChatRoute
  '/app/records': typeof AppRecordsRoute
  '/app/': typeof AppIndexRoute
  '/app/appointments/$id': typeof AppAppointmentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/book': typeof AppBookRoute
  '/app/chat': typeof AppChatRoute
  '/app/records': typeof AppRecordsRoute
  '/app': typeof AppIndexRoute
  '/app/appointments/$id': typeof AppAppointmentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/book': typeof AppBookRoute
  '/app/chat': typeof AppChatRoute
  '/app/records': typeof AppRecordsRoute
  '/app/': typeof AppIndexRoute
  '/app/appointments/$id': typeof AppAppointmentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app/book'
    | '/app/chat'
    | '/app/records'
    | '/app/'
    | '/app/appointments/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/book'
    | '/app/chat'
    | '/app/records'
    | '/app'
    | '/app/appointments/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/app/book'
    | '/app/chat'
    | '/app/records'
    | '/app/'
    | '/app/appointments/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AppBookRoute: typeof AppBookRoute
  AppChatRoute: typeof AppChatRoute
  AppRecordsRoute: typeof AppRecordsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAppointmentsIdRoute: typeof AppAppointmentsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/records': {
      id: '/app/records'
      path: '/app/records'
      fullPath: '/app/records'
      preLoaderRoute: typeof AppRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/app/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/book': {
      id: '/app/book'
      path: '/app/book'
      fullPath: '/app/book'
      preLoaderRoute: typeof AppBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/appointments/$id': {
      id: '/app/appointments/$id'
      path: '/app/appointments/$id'
      fullPath: '/app/appointments/$id'
      preLoaderRoute: typeof AppAppointmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AppBookRoute: AppBookRoute,
  AppChatRoute: AppChatRoute,
  AppRecordsRoute: AppRecordsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAppointmentsIdRoute: AppAppointmentsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
